export * from './isArray';
export * from './isArrayOrObject';
export * from './isDate';
export * from './isFunction';
export * from './isMap';
export * from './isObject';
export * from './isPlainObject';
export * from './isPrimitive';
export * from './isSet';
